[build]
  command = "gatsby build"
  functions = "netlify/functions"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby"

[plugins.inputs]
  enable = true

[plugins.inputs.postBuild]
  enable = true

[[plugins]]
  package = "netlify-plugin-cypress"

[plugins.inputs]
  enable = false
